name: Test

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
      - name: Check Formatting
        run: cargo fmt --all -- --check